"""Convert a Q8_0 model + tokenizer into a C header for firmware embedding.

On ESP32, `const` arrays live in flash (rodata) and are memory-mapped through
the flash cache — the same hardware path as esp_partition_mmap(), with none of
the partition-table/esptool workflow. Deploying a new model = regenerate the
header, hit Upload.

Usage:
    uv run python tools/export_header.py models/stories260K_q80.bin models/tok512.bin
    # writes firmware/tinyllm_arduino/model_data.h by default (-o to override)
"""
import argparse
import os


def emit_array(f, name: str, data: bytes) -> None:
    f.write(f"__attribute__((aligned(16))) const uint8_t {name}[{len(data)}] = {{\n")
    for i in range(0, len(data), 16):
        chunk = ",".join(f"0x{b:02x}" for b in data[i:i + 16])
        f.write(f"  {chunk},\n")
    f.write("};\n")
    f.write(f"const uint32_t {name}_LEN = {len(data)};\n\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("model", help="Q8_0 v2 .bin (from tools/quantize.py)")
    parser.add_argument("tokenizer", help="tokenizer .bin (e.g. models/tok512.bin)")
    parser.add_argument("-o", "--output",
                        default=os.path.join("firmware", "tinyllm_arduino", "model_data.h"))
    args = parser.parse_args()

    with open(args.model, "rb") as f:
        model = f.read()
    if model[:4] != b"24ka":  # magic 0x616b3432 ("ak42"), little-endian on disk
        raise SystemExit(f"{args.model} is not a v2 (Q8_0) model file — quantize it first")
    with open(args.tokenizer, "rb") as f:
        tok = f.read()

    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, "w", newline="\n") as f:
        f.write("// generated by tools/export_header.py — do not edit\n")
        f.write(f"// model: {os.path.basename(args.model)} ({len(model)} bytes)"
                f"  tokenizer: {os.path.basename(args.tokenizer)} ({len(tok)} bytes)\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        emit_array(f, "MODEL_DATA", model)
        emit_array(f, "TOKENIZER_DATA", tok)

    print(f"wrote {args.output}: model {len(model)} B + tokenizer {len(tok)} B")


if __name__ == "__main__":
    main()
